name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"  # Match version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker Image Tags
        id: get_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "TAGS=milindpatel63/samba-monitor:${VERSION},milindpatel63/samba-monitor:latest" >> $GITHUB_ENV
          else
            echo "TAGS=milindpatel63/samba-monitor:latest" >> $GITHUB_ENV
          fi

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
